### PR TITLE
Add a toleration to avoid removing the taint on the master nodes

### PR DESCRIPTION
**Pull request by sguyennet**
**What this PR does / why we need it**:

Add a toleration to the daemonset to allow scheduling of the pods without removing the taint on the master nodes.

With this toleration, you don't need to do "kubectl taint nodes --all node-role.kubernetes.io/master-" as described in the README:

https://github.com/vmware/kubernetes/blob/enable-vcp-uxi/README.md

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by divyenpatel** [comment]
@sguyennet change looks good to me.
I will update documentation.

**Comment by sguyennet** [comment]
Hi,

I just noticed that you updated the documentation, but you didn't push a new image on Docker hub:

https://hub.docker.com/r/cnastorage/enablevcp/tags/

The modification I did is embedded in the Docker images, therefore you should build a new one and push it to Docker hub.

**Comment by divyenpatel** [comment]
@sguyennet I will build and upload new image today.

**Pull request merged**
