### PR TITLE
Updated DeleteVolume implementation to use the cache and workspace

### PR DESCRIPTION
**Pull request by SandeepPissay**
Summary:
- Updated the DeleteVolume implementation to use the datacenter from Workspace in vsphere.conf for performing volume deletion.
- Removed some logs that were marked for removal.

Testing done:
- Created storage class and PVC that uses the storage class. Validated that this created the disk successfully. Deleted the PVC and validated that the DeleteVolume is deleting the disk properly.

### CODE REVIEW

**Comment by SandeepPissay** [comment]
@BaluDontu @abrarshivani @rohitjogvmw 

Please review.

**Comment by SandeepPissay** [comment]
@rohitjogvmw Can you approve this PR?

**Comment by BaluDontu** [comment]
I assumed the workspace struct would only be used for creating dummy VM's and not for any others.
Instead I was thinking you should use the datacenter where the master is, for deleting the volume.
Between your existing PR works too since all VC's have access to datastore. But I am slightly more inclined towards using a datacenter where master is rather than workspace. 

Also can you add a comment to workspace and what exactly is used for as part of your PR.

**Comment by SandeepPissay** [comment]
@BaluDontu workspace struct is used to create volume. We have 2 ways of creating the volume - VirtualDiskManager.createDisk and createVm. Its better to be consistent on which VC/DC is used for this purpose.

We discussed that relying on master's location is not a good idea as the master VM could be moved to another VC. Also, it may complicate things when we support multi-master.

I'll add a comment for workspace struct for this.

**Comment by BaluDontu** [comment]
"We discussed that relying on master's location is not a good idea as the master VM could be moved to another VC. Also, it may complicate things when we support multi-master".

It doesn't matter even if the master VM moves out to another VC. We only support shared datastores. So in this case, it won't create any problem.

**Pull request merged**
